spring:
  application.name: ozonosfer-test
  redis:
    host: localhost
    port: 6379
    timeout: 1000
ozonosfer:
  implementation: redis
  seconds: 60
  limit: 1000
  toggling: white-list
redis:
  sentinel: false